// see: https://gist.github.com/zspine/2365808
export const NATIONALITIES = [
  { id: 'AD', country: 'Andorra', nationality: 'Andorran' },
  { id: 'AE', country: 'United Arab Emirates', nationality: 'Emirati' },
  { id: 'AF', country: 'Afghanistan', nationality: 'Afghan' },
  {
    id: 'AG',
    country: 'Antigua and Barbuda',
    nationality: 'Antiguan, Barbudan',
  },
  { id: 'AI', country: 'Anguilla', nationality: 'Anguillian' },
  { id: 'AL', country: 'Albania', nationality: 'Albanian' },
  { id: 'AM', country: 'Armenia', nationality: 'Armenian' },
  { id: 'AN', country: 'Netherlands Antilles', nationality: 'Dutch' },
  { id: 'AO', country: 'Angola', nationality: 'Angolan' },
  { id: 'AQ', country: 'Antarctica', nationality: '???' },
  { id: 'AR', country: 'Argentina', nationality: 'Argentinean' },
  { id: 'AS', country: 'American Samoa', nationality: 'American Samoan' },
  { id: 'AT', country: 'Austria', nationality: 'Austrian' },
  { id: 'AU', country: 'Australia', nationality: 'Australian' },
  { id: 'AW', country: 'Aruba', nationality: 'Aruban' },
  { id: 'AX', country: 'Åland Islands', nationality: 'Swedish' },
  { id: 'AZ', country: 'Azerbaijan', nationality: 'Azerbaijani' },
  {
    id: 'BA',
    country: 'Bosnia and Herzegovina',
    nationality: 'Bosnian, Herzegovinian',
  },
  { id: 'BB', country: 'Barbados', nationality: 'Barbadian' },
  { id: 'BD', country: 'Bangladesh', nationality: 'Bangladeshi' },
  { id: 'BE', country: 'Belgium', nationality: 'Belgian' },
  { id: 'BF', country: 'Burkina Faso', nationality: 'Burkinabe' },
  { id: 'BG', country: 'Bulgaria', nationality: 'Bulgarian' },
  { id: 'BH', country: 'Bahrain', nationality: 'Bahraini' },
  { id: 'BI', country: 'Burundi', nationality: 'Burundian' },
  { id: 'BJ', country: 'Benin', nationality: 'Beninese' },
  {
    id: 'BL',
    country: 'Saint Barthélemy',
    nationality: 'Saint Barthélemy Islander',
  },
  { id: 'BM', country: 'Bermuda', nationality: 'Bermudian' },
  { id: 'BN', country: 'Brunei', nationality: 'Bruneian' },
  { id: 'BO', country: 'Bolivia', nationality: 'Bolivian' },
  { id: 'BQ', country: 'British Antarctic Territory', nationality: 'Dutch' },
  { id: 'BR', country: 'Brazil', nationality: 'Brazilian' },
  { id: 'BS', country: 'Bahamas', nationality: 'Bahamian' },
  { id: 'BT', country: 'Bhutan', nationality: 'Bhutanese' },
  { id: 'BV', country: 'Bouvet Island', nationality: '???' },
  { id: 'BW', country: 'Botswana', nationality: 'Motswana' },
  { id: 'BY', country: 'Belarus', nationality: 'Belarusian' },
  { id: 'BZ', country: 'Belize', nationality: 'Belizean' },
  { id: 'CA', country: 'Canada', nationality: 'Canadian' },
  {
    id: 'CC',
    country: 'Cocos [Keeling] Islands',
    nationality: 'Cocos Islander',
  },
  { id: 'CD', country: 'Congo - Kinshasa', nationality: 'Congolese' },
  {
    id: 'CF',
    country: 'Central African Republic',
    nationality: 'Central African',
  },
  { id: 'CG', country: 'Congo - Brazzaville', nationality: 'Congolese' },
  { id: 'CH', country: 'Switzerland', nationality: 'Swiss' },
  { id: 'CI', country: 'Côte d’Ivoire', nationality: 'Ivorian' },
  { id: 'CK', country: 'Cook Islands', nationality: 'Cook Islander' },
  { id: 'CL', country: 'Chile', nationality: 'Chilean' },
  { id: 'CM', country: 'Cameroon', nationality: 'Cameroonian' },
  { id: 'CN', country: 'China', nationality: 'Chinese' },
  { id: 'CO', country: 'Colombia', nationality: 'Colombian' },
  { id: 'CR', country: 'Costa Rica', nationality: 'Costa Rican' },
  {
    id: 'CS',
    country: 'Serbia and Montenegro',
    nationality: 'Montenegrins, Serbs',
  },
  { id: 'CT', country: 'Canton and Enderbury Islands', nationality: '???' },
  { id: 'CU', country: 'Cuba', nationality: 'Cuban' },
  { id: 'CV', country: 'Cape Verde', nationality: 'Cape Verdian' },
  { id: 'CW', country: 'Curaçao', nationality: 'Curaçaoan' },
  { id: 'CX', country: 'Christmas Island', nationality: 'Christmas Island' },
  { id: 'CY', country: 'Cyprus', nationality: 'Cypriot' },
  { id: 'CZ', country: 'Czech Republic', nationality: 'Czech' },
  { id: 'DE', country: 'Germany', nationality: 'German' },
  { id: 'DJ', country: 'Djibouti', nationality: 'Djibouti' },
  { id: 'DK', country: 'Denmark', nationality: 'Danish' },
  { id: 'DM', country: 'Dominica', nationality: 'Dominican' },
  { id: 'DO', country: 'Dominican Republic', nationality: 'Dominican' },
  { id: 'DZ', country: 'Algeria', nationality: 'Algerian' },
  { id: 'EC', country: 'Ecuador', nationality: 'Ecuadorean' },
  { id: 'EE', country: 'Estonia', nationality: 'Estonian' },
  { id: 'EG', country: 'Egypt', nationality: 'Egyptian' },
  { id: 'EH', country: 'Western Sahara', nationality: 'Sahrawi' },
  { id: 'ER', country: 'Eritrea', nationality: 'Eritrean' },
  { id: 'ES', country: 'Spain', nationality: 'Spanish' },
  { id: 'ET', country: 'Ethiopia', nationality: 'Ethiopian' },
  { id: 'FI', country: 'Finland', nationality: 'Finnish' },
  { id: 'FJ', country: 'Fiji', nationality: 'Fijian' },
  { id: 'FK', country: 'Falkland Islands', nationality: 'Falkland Islander' },
  { id: 'FM', country: 'Micronesia', nationality: 'Micronesian' },
  { id: 'FO', country: 'Faroe Islands', nationality: 'Faroese' },
  {
    id: 'FQ',
    country: 'French Southern and Antarctic Territories',
    nationality: '???',
  },
  { id: 'FR', country: 'France', nationality: 'French' },
  { id: 'FX', country: 'Metropolitan France', nationality: '???' },
  { id: 'GA', country: 'Gabon', nationality: 'Gabonese' },
  { id: 'GB', country: 'United Kingdom', nationality: 'British' },
  { id: 'GD', country: 'Grenada', nationality: 'Grenadian' },
  { id: 'GE', country: 'Georgia', nationality: 'Georgian' },
  { id: 'GF', country: 'French Guiana', nationality: 'French Guianese' },
  { id: 'GG', country: 'Guernsey', nationality: 'Channel Islander' },
  { id: 'GH', country: 'Ghana', nationality: 'Ghanaian' },
  { id: 'GI', country: 'Gibraltar', nationality: 'Gibraltarian' },
  { id: 'GL', country: 'Greenland', nationality: 'Greenlandic' },
  { id: 'GM', country: 'Gambia', nationality: 'Gambian' },
  { id: 'GN', country: 'Guinea', nationality: 'Guinean' },
  { id: 'GP', country: 'Guadeloupe', nationality: 'Guadeloupean' },
  { id: 'GQ', country: 'Equatorial Guinea', nationality: 'Equatorial Guinean' },
  { id: 'GR', country: 'Greece', nationality: 'Greek' },
  {
    id: 'GS',
    country: 'South Georgia and the South Sandwich Islands',
    nationality: 'South Georgia Islander',
  },
  { id: 'GT', country: 'Guatemala', nationality: 'Guatemalan' },
  { id: 'GU', country: 'Guam', nationality: 'Guamanian' },
  { id: 'GW', country: 'Guinea-Bissau', nationality: 'Bissau-Guinean' },
  { id: 'GY', country: 'Guyana', nationality: 'Guyanese' },
  { id: 'HK', country: 'Hong Kong', nationality: 'Hong Konger' },
  {
    id: 'HM',
    country: 'Heard Island and McDonald Islands',
    nationality: '???',
  },
  { id: 'HN', country: 'Honduras', nationality: 'Honduran' },
  { id: 'HR', country: 'Croatia', nationality: 'Croatian' },
  { id: 'HT', country: 'Haiti', nationality: 'Haitian' },
  { id: 'HU', country: 'Hungary', nationality: 'Hungarian' },
  { id: 'ID', country: 'Indonesia', nationality: 'Indonesian' },
  { id: 'IE', country: 'Ireland', nationality: 'Irish' },
  { id: 'IL', country: 'Israel', nationality: 'Israeli' },
  { id: 'IM', country: 'Isle of Man', nationality: 'Manx' },
  { id: 'IN', country: 'India', nationality: 'Indian' },
  { id: 'IO', country: 'British Indian Ocean Territory', nationality: '???' },
  { id: 'IQ', country: 'Iraq', nationality: 'Iraqi' },
  { id: 'IR', country: 'Iran', nationality: 'Iranian' },
  { id: 'IS', country: 'Iceland', nationality: 'Icelandic' },
  { id: 'IT', country: 'Italy', nationality: 'Italian' },
  { id: 'JE', country: 'Jersey', nationality: 'Channel Islander' },
  { id: 'JM', country: 'Jamaica', nationality: 'Jamaican' },
  { id: 'JO', country: 'Jordan', nationality: 'Jordanian' },
  { id: 'JP', country: 'Japan', nationality: 'Japanese' },
  { id: 'KE', country: 'Kenya', nationality: 'Kenyan' },
  { id: 'KG', country: 'Kyrgyzstan', nationality: 'Kyrgyz' },
  { id: 'KH', country: 'Cambodia', nationality: 'Cambodian' },
  { id: 'KI', country: 'Kiribati', nationality: 'I-Kiribati' },
  { id: 'KM', country: 'Comoros', nationality: 'Comorian' },
  {
    id: 'KN',
    country: 'Saint Kitts and Nevis',
    nationality: 'Kittitian or Nevisian',
  },
  { id: 'KP', country: 'North Korea', nationality: 'North Korean' },
  { id: 'KR', country: 'South Korea', nationality: 'South Korean' },
  { id: 'KW', country: 'Kuwait', nationality: 'Kuwaiti' },
  { id: 'KY', country: 'Cayman Islands', nationality: 'Caymanian' },
  { id: 'KZ', country: 'Kazakhstan', nationality: 'Kazakhstani' },
  { id: 'LA', country: 'Laos', nationality: 'Lao' },
  { id: 'LB', country: 'Lebanon', nationality: 'Lebanese' },
  { id: 'LC', country: 'Saint Lucia', nationality: 'Saint Lucian' },
  { id: 'LI', country: 'Liechtenstein', nationality: 'Liechtensteiner' },
  { id: 'LK', country: 'Sri Lanka', nationality: 'Sri Lankan' },
  { id: 'LR', country: 'Liberia', nationality: 'Liberian' },
  { id: 'LS', country: 'Lesotho', nationality: 'Basotho' },
  { id: 'LT', country: 'Lithuania', nationality: 'Lithuanian' },
  { id: 'LU', country: 'Luxembourg', nationality: 'Luxembourgish' },
  { id: 'LV', country: 'Latvia', nationality: 'Latvian' },
  { id: 'LY', country: 'Libya', nationality: 'Libyan' },
  { id: 'MA', country: 'Morocco', nationality: 'Moroccan' },
  { id: 'MC', country: 'Monaco', nationality: 'Monegasque' },
  { id: 'MD', country: 'Moldova', nationality: 'Moldovan' },
  { id: 'ME', country: 'Montenegro', nationality: 'Montenegrin' },
  { id: 'MF', country: 'Saint Martin', nationality: 'Saint-Martinoise' },
  { id: 'MG', country: 'Madagascar', nationality: 'Malagasy' },
  { id: 'MH', country: 'Marshall Islands', nationality: 'Marshallese' },
  { id: 'MK', country: 'North Macedonia', nationality: 'Macedonian' },
  { id: 'ML', country: 'Mali', nationality: 'Malian' },
  { id: 'MM', country: 'Myanmar', nationality: 'Burmese' },
  { id: 'MN', country: 'Mongolia', nationality: 'Mongolian' },
  { id: 'MO', country: 'Macao', nationality: 'Macanese' },
  {
    id: 'MP',
    country: 'Northern Mariana Islands',
    nationality: 'Northern Marianan',
  },
  { id: 'MQ', country: 'Martinique', nationality: 'Martinican' },
  { id: 'MR', country: 'Mauritania', nationality: 'Mauritanian' },
  { id: 'MS', country: 'Montserrat', nationality: 'Montserratian' },
  { id: 'MT', country: 'Malta', nationality: 'Maltese' },
  { id: 'MU', country: 'Mauritius', nationality: 'Mauritian' },
  { id: 'MV', country: 'Maldives', nationality: 'Maldivian' },
  { id: 'MW', country: 'Malawi', nationality: 'Malawian' },
  { id: 'MX', country: 'Mexico', nationality: 'Mexican' },
  { id: 'MY', country: 'Malaysia', nationality: 'Malaysian' },
  { id: 'MZ', country: 'Mozambique', nationality: 'Mozambican' },
  { id: 'NA', country: 'Namibia', nationality: 'Namibian' },
  { id: 'NC', country: 'New Caledonia', nationality: 'New Caledonian' },
  { id: 'NE', country: 'Niger', nationality: 'Nigerien' },
  { id: 'NF', country: 'Norfolk Island', nationality: 'Norfolk Islander' },
  { id: 'NG', country: 'Nigeria', nationality: 'Nigerian' },
  { id: 'NI', country: 'Nicaragua', nationality: 'Nicaraguan' },
  { id: 'NL', country: 'Netherlands', nationality: 'Dutch' },
  { id: 'NO', country: 'Norway', nationality: 'Norwegian' },
  { id: 'NP', country: 'Nepal', nationality: 'Nepalese' },
  { id: 'NR', country: 'Nauru', nationality: 'Nauruan' },
  { id: 'NU', country: 'Niue', nationality: 'Niuean' },
  { id: 'NZ', country: 'New Zealand', nationality: 'New Zealander' },
  { id: 'OM', country: 'Oman', nationality: 'Omani' },
  { id: 'PA', country: 'Panama', nationality: 'Panamanian' },
  { id: 'PE', country: 'Peru', nationality: 'Peruvian' },
  { id: 'PF', country: 'French Polynesia', nationality: 'French Polynesian' },
  { id: 'PG', country: 'Papua New Guinea', nationality: 'Papua New Guinean' },
  { id: 'PH', country: 'Philippines', nationality: 'Filipino' },
  { id: 'PK', country: 'Pakistan', nationality: 'Pakistani' },
  { id: 'PL', country: 'Poland', nationality: 'Polish' },
  {
    id: 'PM',
    country: 'Saint Pierre and Miquelon',
    nationality: 'Saint-Pierrais or Miquelonnais',
  },
  { id: 'PN', country: 'Pitcairn', nationality: 'Pitcairn Islander' },
  { id: 'PR', country: 'Puerto Rico', nationality: 'Puerto Rican' },
  { id: 'PT', country: 'Portugal', nationality: 'Portuguese' },
  { id: 'PW', country: 'Palau', nationality: 'Palauan' },
  { id: 'PY', country: 'Paraguay', nationality: 'Paraguayan' },
  { id: 'QA', country: 'Qatar', nationality: 'Qatari' },
  { id: 'RE', country: 'Réunion', nationality: 'Réunionese' },
  { id: 'RO', country: 'Romania', nationality: 'Romanian' },
  { id: 'RS', country: 'Serbia', nationality: 'Serbian' },
  { id: 'RU', country: 'Russia', nationality: 'Russian' },
  { id: 'RW', country: 'Rwanda', nationality: 'Rwandan' },
  { id: 'SA', country: 'Saudi Arabia', nationality: 'Saudi Arabian' },
  { id: 'SB', country: 'Solomon Islands', nationality: 'Solomon Islander' },
  { id: 'SC', country: 'Seychelles', nationality: 'Seychellois' },
  { id: 'SD', country: 'Sudan', nationality: 'Sudanese' },
  { id: 'SE', country: 'Sweden', nationality: 'Swedish' },
  { id: 'SG', country: 'Singapore', nationality: 'Singaporean' },
  {
    id: 'SH',
    country: 'Saint Helena, Ascension and Tristan da Cunha',
    nationality: 'Saint Helenian',
  },
  { id: 'SI', country: 'Slovenia', nationality: 'Slovenian' },
  { id: 'SJ', country: 'Svalbard and Jan Mayen', nationality: '???' },
  { id: 'SK', country: 'Slovakia', nationality: 'Slovak' },
  { id: 'SL', country: 'Sierra Leone', nationality: 'Sierra Leonean' },
  { id: 'SM', country: 'San Marino', nationality: 'Sammarinese' },
  { id: 'SN', country: 'Senegal', nationality: 'Senegalese' },
  { id: 'SO', country: 'Somalia', nationality: 'Somali' },
  { id: 'SR', country: 'Suriname', nationality: 'Surinamese' },
  { id: 'SS', country: 'South Sudan', nationality: 'South Sudanese' },
  { id: 'ST', country: 'Sao Tome and Principe', nationality: 'Sao Tomean' },
  { id: 'SV', country: 'El Salvador', nationality: 'Salvadoran' },
  { id: 'SX', country: 'Sint Maarten', nationality: 'Sint Maarten' },
  { id: 'SY', country: 'Syria', nationality: 'Syrian' },
  { id: 'SZ', country: 'Eswatini', nationality: 'Swazi' },
  {
    id: 'TC',
    country: 'Turks and Caicos Islands',
    nationality: 'Turks and Caicos Islander',
  },
  { id: 'TD', country: 'Chad', nationality: 'Chadian' },
  { id: 'TF', country: 'French Southern Territories', nationality: '???' },
  { id: 'TG', country: 'Togo', nationality: 'Togolese' },
  { id: 'TH', country: 'Thailand', nationality: 'Thai' },
  { id: 'TJ', country: 'Tajikistan', nationality: 'Tajikistani' },
  { id: 'TK', country: 'Tokelau', nationality: 'Tokelauan' },
  { id: 'TL', country: 'Timor-Leste', nationality: 'Timorese' },
  { id: 'TM', country: 'Turkmenistan', nationality: 'Turkmen' },
  { id: 'TN', country: 'Tunisia', nationality: 'Tunisian' },
  { id: 'TO', country: 'Tonga', nationality: 'Tongan' },
  { id: 'TR', country: 'Turkey', nationality: 'Turkish' },
  {
    id: 'TT',
    country: 'Trinidad and Tobago',
    nationality: 'Trinidadian or Tobagonian',
  },
  { id: 'TV', country: 'Tuvalu', nationality: 'Tuvaluan' },
  { id: 'TW', country: 'Taiwan', nationality: 'Taiwanese' },
  { id: 'TZ', country: 'Tanzania', nationality: 'Tanzanian' },
  { id: 'UA', country: 'Ukraine', nationality: 'Ukrainian' },
  { id: 'UG', country: 'Uganda', nationality: 'Ugandan' },
  {
    id: 'UM',
    country: 'United States Minor Outlying Islands',
    nationality: '???',
  },
  { id: 'US', country: 'United States', nationality: 'American' },
  { id: 'UY', country: 'Uruguay', nationality: 'Uruguayan' },
  { id: 'UZ', country: 'Uzbekistan', nationality: 'Uzbekistani' },
  { id: 'VA', country: 'Vatican City', nationality: 'Vatican' },
  {
    id: 'VC',
    country: 'Saint Vincent and the Grenadines',
    nationality: 'Vincentian',
  },
  { id: 'VE', country: 'Venezuela', nationality: 'Venezuelan' },
  {
    id: 'VG',
    country: 'British Virgin Islands',
    nationality: 'British Virgin Islander',
  },
  {
    id: 'VI',
    country: 'United States Virgin Islands',
    nationality: 'U.S. Virgin Islander',
  },
  { id: 'VN', country: 'Vietnam', nationality: 'Vietnamese' },
  { id: 'VU', country: 'Vanuatu', nationality: 'Ni-Vanuatu' },
  {
    id: 'WF',
    country: 'Wallis and Futuna',
    nationality: 'Wallisian or Futunan',
  },
  { id: 'WS', country: 'Samoa', nationality: 'Samoan' },
  { id: 'YE', country: 'Yemen', nationality: 'Yemeni' },
  { id: 'YT', country: 'Mayotte', nationality: 'Mahoran' },
  { id: 'ZA', country: 'South Africa', nationality: 'South African' },
  { id: 'ZM', country: 'Zambia', nationality: 'Zambian' },
  { id: 'ZW', country: 'Zimbabwe', nationality: 'Zimbabwean' },
];
